server:
  port: 7504
spring:
  application:
    name: blogservice # 服务名称
  datasource:
    url: jdbc:mysql://10.129.0.31:3306/EBed?useSSL=false
    username: root
    password: Dyp20001209
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 10.129.0.31
    port: 6379
    password: Dyp20001209
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
  rabbitmq:
    host: 10.129.0.31 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: howard1209a # 用户名
    password: Dyp20001209 # 密码
  cloud:
    nacos:
      server-addr: 10.129.0.31:8848
mybatis:
  type-aliases-package: org.howard1209a.blog.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    cn.itcast: debug
    org.mybatis: DEBUG

