server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  redis:
    host: 10.129.0.31
    port: 6379
    password: Dyp20001209
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
  cloud:
    nacos:
      server-addr: 10.129.0.31:8848
    gateway:
      routes: # 网关路由配置
        - id: static-web # 路由id，自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://staticweb # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/static/** # 这个是按照路径匹配，只要以/user/开头就符合要求
        - id: user-service # 路由id，自定义，只要唯一即可
          uri: lb://userservice # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/** # 这个是按照路径匹配，只要以/user/开头就符合要求
        - id: file-service # 路由id，自定义，只要唯一即可
          uri: lb://fileservice # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/file/** # 这个是按照路径匹配，只要以/user/开头就符合要求
        - id: blog-service # 路由id，自定义，只要唯一即可
          uri: lb://blogservice # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/blog/** # 这个是按照路径匹配，只要以/user/开头就符合要求