server:
  port: 7505
spring:
  application:
    name: searchservice # 服务名称
  rabbitmq:
    host: 10.129.0.31 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: howard1209a # 用户名
    password: Dyp20001209 # 密码
  redis:
    host: 10.129.0.31
    port: 6379
    password: Dyp20001209
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
  cloud:
    nacos:
      server-addr: 10.129.0.31:8848
logging:
  level:
    cn.itcast: debug
    org.mybatis: DEBUG

